
cd build_darwin_x86_64_appleclang/Release
# cd build_linux_x86_64_gnu

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/stesla/source/stesla.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/stesla.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/stesla.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/stesla/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/stesla/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/sphere-bot/source/sphere-bot.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/sphere-bot.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/sphere-bot.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/sphere-bot/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/sphere-bot/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/crystal-stone/source/crystal-stone.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/crystal-stone.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/crystal-stone.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/crystal-stone/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/crystal-stone/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/gecko/source/gecko.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/gecko.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/gecko.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/gecko/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/gecko/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/integrated-thermostatic-valve-slim-head/source/integrated-thermostatic-valve-slim-head.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/integrated-thermostatic-valve-slim-head.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/integrated-thermostatic-valve-slim-head.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/integrated-thermostatic-valve-slim-head/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/integrated-thermostatic-valve-slim-head/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/run-hedgehog-run/source/run-hedgehog-run.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/run-hedgehog-run.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/run-hedgehog-run.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/run-hedgehog-run/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/run-hedgehog-run/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/anak-the-lizardman/source/anak-the-lizardman.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/anak-the-lizardman.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/anak-the-lizardman.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/anak-the-lizardman/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/anak-the-lizardman/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/colt-rebel-357/source/colt-rebel-357.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/colt-rebel-357.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/colt-rebel-357.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/colt-rebel-357/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/colt-rebel-357/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/dji/source/dji.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/dji.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/dji.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/dji/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/dji/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/3000-followers-milestone/source/3000-followers-milestone.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/3000-followers-milestone.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/3000-followers-milestone.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/3000-followers-milestone/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/3000-followers-milestone/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/futuristic-safe/source/futuristic-safe.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/futuristic-safe.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/futuristic-safe.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/futuristic-safe/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/futuristic-safe/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/vanille-flirty-animation/source/vanille-flirty-animation.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/vanille-flirty-animation.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/vanille-flirty-animation.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/vanille-flirty-animation/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/vanille-flirty-animation/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/awesome-mix-guardians-of-the-galaxy/source/awesome-mix-guardians-of-the-galaxy.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/awesome-mix-guardians-of-the-galaxy.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/awesome-mix-guardians-of-the-galaxy.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/awesome-mix-guardians-of-the-galaxy/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/awesome-mix-guardians-of-the-galaxy/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/k07-drone/source/k07-drone.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/k07-drone.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/k07-drone.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/k07-drone/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/k07-drone/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/opel-gt-retopo/source/opel-gt-retopo.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/opel-gt-retopo.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/opel-gt-retopo.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/opel-gt-retopo/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/opel-gt-retopo/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/rusty-mecha/source/rusty-mecha.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/rusty-mecha.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/rusty-mecha.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/strusty-mechaesla/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/rusty-mecha/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/sci-fi-girl/source/sci-fi-girl.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/sci-fi-girl.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/sci-fi-girl.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/sci-fi-girl/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/sci-fi-girl/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/littlest-tokyo/source/littlest-tokyo.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/littlest-tokyo.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/littlest-tokyo.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/littlest-tokyo/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/littlest-tokyo/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/ice-cream-truck/source/ice-cream-truck.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/ice-cream-truck.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/ice-cream-truck.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/ice-cream-truck/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/ice-cream-truck/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/littlest-tokyo/source/littlest-tokyo.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/littlest-tokyo.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/littlest-tokyo.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/littlest-tokyo/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/littlest-tokyo/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/arex-rex-zero1/source/arex-rex-zero1.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/arex-rex-zero1.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/arex-rex-zero1.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/arex-rex-zero1/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/arex-rex-zero1/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/flare-gun/source/flare-gun.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/flare-gun.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/flare-gun.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/flare-gun/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/flare-gun/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/lovecraftian/source/lovecraftian.obj" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/lovecraftian.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/flovecraftian.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/lovecraftian/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/lovecraftian/scene.gltf"

./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/izzy-animated-female-character-free-download/source/izzy-animated-female-character-free-download.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/izzy.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/izzy.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/izzy-animated-female-character-free-download/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/izzy-animated-female-character-free-download/scene.gltf"

# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/subzero-b-posicao-vitoria/source/subzero-b-posicao-vitoria.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/subzero.fbxp" --resample-framerate 0 -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/subzero.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/subzero-b-posicao-vitoria/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/subzero-b-posicao-vitoria/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/forest-house/source/forest-house.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/forest-house.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/forest-house.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/forest-house/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/forest-house/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/littlest-tokyo/source/littlest-tokyo.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/littlest-tokyo.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/littlest-tokyo.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/littlest-tokyo/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/littlest-tokyo/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/mountain-king/source/mountain-king.obj" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/mountain-king.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/mountain-king.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/mountain-king/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/mountain-king/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/rainier-ak-3d/source/rainier-ak-3d.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/rainier-ak-3d.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/rainier-ak-3d.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/rainier-ak-3d/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/rainier-ak-3d/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/bristleback-dota-fan-art/source/bristleback-dota-fan-art.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/bristleback.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/bristleback.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/bristleback-dota-fan-art/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/bristleback-dota-fan-art/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/izzy-animated-female-character-free-download/source/izzy-animated-female-character-free-download.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/izzy.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/izzy.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/izzy-animated-female-character-free-download/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/izzy-animated-female-character-free-download/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/subzero-b-posicao-vitoria/source/subzero-b-posicao-vitoria.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/subzero.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/subzero.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/subzero-b-posicao-vitoria/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/subzero-b-posicao-vitoria/scene.gltf"

# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/warmonger_sword/source/Warmonger_Posed.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/warmonger_sword.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/warmonger_sword.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/warmonger_sword/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/warmonger_sword/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/dreamsong/source/BOTI_Dreamsong_Bridge.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/dreamsong.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/dreamsong.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/dreamsong/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/dreamsong/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/zis-101a-sport-1938/source/ZIS101Sport.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/zis-101a-sport-1938.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/zis-101a-sport-1938.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/zis-101a-sport-1938/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/zis-101a-sport-1938/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/voodoo-skull/source/VoodooSkull.obj" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/voodoo-skull.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/voodoo-skull.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/voodoo-skull/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/voodoo-skull/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/skull-salazar/source/model.dae" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/skull-salazar.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/skull-salazar.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/skull-salazar/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/skull-salazar/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/paladins-book/source/book_low_sketch.obj" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/paladins-book.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/paladins-book.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/paladins-book/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/paladins-book/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/cerberusffvii-gun-model-by-andrew-maximov/source/cerberusffvii.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/cerberusffvii-gun-model-by-andrew-maximov.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/cerberusffvii-gun-model-by-andrew-maximov.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/cerberusffvii-gun-model-by-andrew-maximov/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/cerberusffvii-gun-model-by-andrew-maximov/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/9-mm/source/9-mm.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/9-mm.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/9-mm.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/9-mm/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/9-mm/scene.gltf"

# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/wasteland-hunters-vehicule/source/model.dae" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/wasteland-hunters-vehicule.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/wasteland-hunters-vehicule.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/wasteland-hunters-vehicule/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/wasteland-hunters-vehicule/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/snow-road-raw-scan-freebie/source/Road.obj" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/snow-road-raw-scan-freebie.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/snow-road-raw-scan-freebie.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/snow-road-raw-scan-freebie/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/snow-road-raw-scan-freebie/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/skull_salazar_downloadable/source/model.dae" -b -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/skull_salazar.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/skull_salazar.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/skull_salazar_downloadable/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/skull_salazar_downloadable/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/graograman__fur_study/source/LIONSKETCH.fbx" -b -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/graograman.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/graograman.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/graograman__fur_study/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/graograman__fur_study/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/warcraft-draenei-fanart/source/untitled1.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/warcraft-draenei-fanart.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/warcraft-draenei-fanart.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/warcraft-draenei-fanart/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/warcraft-draenei-fanart/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/1972-datsun-240k-gt/source/datsun240k.fbx" -b -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/1972-datsun-240k-gt.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/1972-datsun-240k-gt.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/1972-datsun-240k-gt/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/1972-datsun-240k-gt/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/dreadroamer-free/source/Zbot_Animation.fbx" -b -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/dreadroamer-free.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/dreadroamer-free.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/dreadroamer-free/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/dreadroamer-free/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/knight-artorias/source/Artorias.fbx.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/knight-artorias.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/knight-artorias.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/knight-artorias/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/knight-artorias/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/leather-shoes/source/model.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/leather-shoes.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/leather-shoes.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/leather-shoes/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/leather-shoes/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/terrarium-bot/source/robot_final_low1.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/terrarium-bot.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/terrarium-bot.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/terrarium-bot/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/terrarium-bot/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/car-lego-technic-42010/source/Lego Car.obj" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/car-lego-technic-42010.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/car-lego-technic-42010.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/car-lego-technic-42010/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/car-lego-technic-42010/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/9-mm/source/9mm.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/9-mm.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/9-mm.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/9-mm/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/9-mm/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/colt/source/Colt.obj" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/colt.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/colt.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/colt/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/colt/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/cerberus/source/Cerberus_LP.FBX.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/cerberus.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/cerberus.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/cerberus/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/cerberus/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/gunslinger/source/gunslinger.obj" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/gunslinger.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/gunslinger.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/gunslinger/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/gunslinger/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/pickup-truck/source/PickupTruck.obj" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/pickup-truck.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/pickup-truck.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/pickup-truck/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/pickup-truck/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/rock-jacket-mid-poly/source/rock_jacket_skfb.obj" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/rock-jacket-mid-poly.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/rock-jacket-mid-poly.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/rock-jacket-mid-poly/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/rock-jacket-mid-poly/scene.gltf"
# ./FbxPipelineLauncher -i "/Users/vlad.serhiienko/Projects/Home/Models/mech-m-6k/source/mech-m-6k.fbx" -o "/Users/vlad.serhiienko/Projects/Home/Models/FbxPipeline/mech-m-6k.fbxp" -l "/Users/vlad.serhiienko/Projects/Home/Models/Logs/mech-m-6k.txt" -e "/Users/vlad.serhiienko/Projects/Home/Models/mech-m-6k/**" --script-file "glTFMaterialExtension.py" --script-input "/Users/vlad.serhiienko/Projects/Home/Models/mech-m-6k/scene.gltf"
